AllCops:
  Exclude:
  - 'main.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 130

Style/ClassVars:
  Enabled: false

